config/routes.rb
Rails.application.routes.draw do
  resources :users
  # users_controller
  root "users#index"
  get "/", to: "users#index"
  post "/users", to: "users#create"
  get "/dashboard", to: "home#index"
  
  post "/update", to: "sessions#update"
  get "/createpage", to: "home#createpage"
  post "/sessions", to: "sessions#create"
  get "/admindashboard", to: "admin#admindashboard"
  get "/editadminprofile", to: "admin#editadminprofile"
  get "/adminsettings", to: "admin#adminsettings"
  get "/logout", to: "sessions#destroy"
  get "/adminlogout", to: "sessions#admindestroy"
  
  post "/admin", to: "admin#create"
  get "/subpage", to: "home#subpage"
  get "/admins", to: "admin#admins"
  get "/seo", to: "home#seo"
  get "/listpage", to: "home#listpage"
  get "/pagedata", to: "home#pagedata"
  get "/subpagedata", to: "home#subpagedata"
  post "/home", to: "home#create"
  get "/edit", to: "home#edit"
  get "/admin", to: "users#adminlogin"
  get "/userslist", to: "admin#userslist"
  post "/subpage", to: "home#createsubpage"
  post "/updatepage", to: "home#updatepage"
  post "/updatesubpage", to: "home#updatesubpage"
  post "/updateadminprofile", to: "admin#update"
  get "/deletepage", to: "home#deletepage"
  get "/userlogin", to: "users#userlogin"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "/adminprofile", to: "admin#adminprofile"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/adminprofile.html.erb
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                    <div class="col-md-4">
                        <% if @user.image.attached? %>
                    <%= link_to image_tag(@user.image), :class => "avatar img-circle img-thumbnail" %>
                    <% else %>
                        <img src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png" alt="Avatar" class="avatar">
                        
                    <% end %>
                    <div class="profile-work">
                <p>WORK LINK</p>
                <a style="color: #9a55ff" href="">Website Link</a><br/>
                <a style="color: #9a55ff" href="">Bootsnipp Profile</a><br/>
                <a style="color: #9a55ff" href="">Bootply Profile</a></br></br>
                <p>SKILLS</p>
                <a style="color: #9a55ff" href="">Web Designer</a><br/>
                <a style="color: #9a55ff" href="">Web Developer</a><br/>
                <a style="color: #9a55ff" href="">WordPress</a><br/>
                <a style="color: #9a55ff" href="">WooCommerce</a><br/>
                <a style="color: #9a55ff" href="">PHP, .Net</a><br/>
            </div>
                    </div>
                    <div class="col-md-8">
                    <h1 style="text-align: center; color: #9a55ff">Admin Profile</h1>
                    </br></br></br>
                    <div class="content-wrapper">
                    <div class="row">
                    <div class="col-md-4">
                    <h5>Name</h5></br>
                    <h5>Email</h5></br>
                    <h5>Profession</h5></br>
                    <h5>Phone</h5></br>
                    <h5>Date of birth</h5></br>
                    <h5>Location</h5></br>
                    </div>
                    
                    <div class="col-md-8" style="color: #9a55ff">
                    <h4>Aiswarya P</h4></br>
                    <h4>aiswaryasugathan001@gmail.com</h4></br>
                    <h4>Software Developer</h4></br>
                    <h4>9946873247</h4></br>
                    <h4>1 July 1997</h4></br>
                    <h4>Trivandrum, India</h4></br>
                    </div>
                    </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/adminsettings.html.erb
<div class="content-wrapper">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
            <h2 style="text-align: center; color: #9a55ff">Settings</h2>
            </br></br></br>
            <div class="row">
                <div class="col-md-4">
                <h4>Change your password</h4>
                </div>
                <div class="col-md-4">
                    <button type="submit" value="/password/reset" class="btn btn-gradient-primary mr-2"><a href="/password/reset" style="color:white">Change</a>
                    <% link_to "Forgot your password?", password_reset_path %></button>
                </div>
                <div class="col-md-4">
                
                </div>
            </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/editadminprofile.html.erb
<div class="content-wrapper">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                
            <h2 style="text-align: center; color: #9a55ff">Edit Profile</h2>
        
    <div class="row">
  		<div class="col-sm-3"><!--left col-->
            <div class="text-center">
            </br>
                <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="avatar">
                <h6>Upload a different photo...</h6>
                <input type="file" name="user[image]" >
            </div><br>
        </div><!--/col-3-->
        <div  class="col-sm-1"></div>
    	<div  class="col-sm-8">
            </br>
                <form class="form" action="/updateadminprofile" enctype="multipart/form-data" method="post" id="registrationForm">
                    <div class="form-group">
                        <label for="exampleInputUsername1">First name</label>
                        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
                        <input type="text" class="form-control" name="user[name]" value=<%= @user.name %> id="exampleInputUsername1" placeholder="First name">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="email" class="form-control" name="user[email]" value=<%= @user.email %> id="exampleInputEmail1" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputUsername1">Profession</label>
                        <input type="text" class="form-control" name="user[profession]" value=<%= @user.profession %> id="exampleInputEmail1" placeholder="Profession">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputUsername1">Phone</label>
                        <input type="text" class="form-control" name="user[phone]" value=<%= @user.phone %> id="exampleInputEmail1" placeholder="Phone">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputUsername1">Change Image</label>
                        <input type="file" name="user[image]" >
                    </div>
                    
                    <div class="form-group">
                        <div class="col-xs-12">
                        </br>
                            <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                            <button class="btn btn-light">Cancel</button>      	
                        </div>
                      </div>
              	</form>
                </div>
            </div>  
        </div><!--/col-9-->

        
    </div><!--/row-->
                                                      
</div>
</div>
      

app/views/admin/login.html.erb
<!DOCTYPE html>
<head>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

</head>
<body>
	<div id="login">
    <h3 class="text-center text-white pt-5">Welcome to Ruby CMS APP</h3>
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">
                <div class="login-box col-md-12">
                    <form id="login-form" class="form" action="/sessions" method = "POST">
                        <h3 class="text-center text-info">Admin Login</h3>
                        <div class="form-group">
                            <label for="username" class="text-info">Email:</label><br>
                            <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
                            <input type="text" name="login[email]" id="username" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="password" class="text-info">Password:</label><br>
                            <input type="text" name="login[password]" id="password" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="remember-me" class="text-info"><span>Remember me</span> <span><input id="remember-me" name="remember-me" type="checkbox"></span></label><br>
                            <input type="submit" name="submit" class="btn btn-info btn-md" value="submit">
                        </div>
                        <div id="register-link" class="text-right">
                            <a href="#" class="text-info">Register here</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

app/views/admin/userslist.html.erb
<div class="row">
        <div class="col-12 grid-margin">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Users List</h4>
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th> User ID </th>
                      <th> Name </th>
                      <th> Status </th>
                      <th> Profession </th>
                      <th> Email ID </th>
                    </tr>
                  </thead>
                  <tbody>
                  <% @alluser.each do |user| %>
                    <tr>
                    <td> USER<%= user.id %></td>
                      <td>
                      <% if user.image.attached? %>
                        <%= link_to image_tag(user.image), users_path %>
                      <% else %>
                            <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="Avatar" class="avatar">
                      
                        <% end %> <%= user.name %>
                      </td>
                      
                      <td>
                        <label class="badge badge-gradient-success">DONE</label>
                      </td>
                      <td> <%= user.profession %></td>
                      <td> <%= user.email %></td>
                    </tr>
                    <% end %>
                    
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>